### ISSUE TITLE
git으로 다운받아도 yarn이 안 먹히네요.

### ISSUE THREAD

**Issue by seoh9510** [yangbeom/BugsElectronPlayer#34]
install이라는 것 자체가 없다고 나옵니다!

**Comment by seoh9510** [comment]
그리고 1.2.3 버전에는 resources 등 파일 누락이 많은 것 같습니다 ㅠㅠ

**Comment by yangbeom** [comment]
install은 yarn이 갖고 있는 기능인데 혹시 yarn은 설치하셨나요?

**Comment by yangbeom** [comment]
오랜기간 답변이 없으셔서 우선 Issue를 닫아두겠습니다.
