### ISSUE TITLE
Mac 환경에서 하단부가 스크롤해야 보임

### ISSUE THREAD

**Issue by whdgus906** [yangbeom/BugsElectronPlayer#9]
Mac 환경에서 하단부 로그인 버튼 부분이 스크롤해야 보임
Dock의 아이콘이 적용되지 않음

**Comment by yangbeom** [comment]
[Releases v1.0.2](https://github.com/yangbeom/BugsElectronPlayer/releases/tag/v1.0.2) 에서 수정 완료
